- name: checking whether CentOS-Base.repo exist
  stat:
    path: /etc/yum.repos.d/CentOS-Base.repo
  register: centos_base_repo

- name: configure CentOS-Base.repo
  yum_repository:
    name: "{{ item.name }}"
    file: CentOS-Base
    baseurl: "{{ base_url.url }}/$releasever/{{ item.url_prefix | default(item.name) }}/$basearch/"
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    gpgcheck: yes
    enabled: "{{ item.enabled | default('yes') }}"
    description: "CentOS-$releasever - {{ item.name.capitalize() }}"
  with_items:
    - name: base
      url_prefix: os
    - name: updates
    - name: extras
    - name: centosplus
      enabled: no
  when:
    - centos_base_repo.stat.exists

- name: importing RPM-GPG-KEY-CentOS-7
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
  when:
    - centos_base_repo.stat.exists
      
- name: checking whether epel.repo exists
  stat:
    path: /etc/yum.repos.d/epel.repo
  register: epel_repo

- name: configuring epel.repo
  yum_repository:
    name: "{{ item.name }}"
    file: epel
    description: "Extra Packages for Enterprise Linux 7 - $basearch{{ ' - ' + item.description_suffix if item.description_suffix else '' }}"
    baseurl: "{{ base_url.epel_url }}/$releasever/$basearch"
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
    gpgcheck: yes
    enabled: "{{ item.enabled }}"
  with_items:
    - name: epel
      description_suffix: null
      enabled: yes
    - name: epel-debuginfo
      description_suffix: Debuginfo
      enabled: no
    - name: epel-source
      description_suffix: Source
      enabled: no
  when:
    - epel_repo.stat.exists

- name: importing RPM-GPG-KEY-EPEL-7
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
  when:
    - epel_repo.stat.exists
