# CentOS-OpenShift-Origin36.repo
- name: checking 
  stat:
    path: /etc/yum.repos.d/CentOS-OpenShift-Origin36.repo
  register: openshift36_repo

- name: configure CentOS-OpenShift-Origin36.repo
  yum_repository:
    name: "{{ item.name }}"
    file: CentOS-OpenShift-Origin36
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-PaaS"
    gpgcheck: "{{ item.gpgcheck | default('yes') }}"
    enabled: "{{ item.enabled }}"
  with_items:
    - name: centos-openshift-origin36
      description: CentOS OpenShift Origin
      baseurl: "{{ base_url.url }}/7/paas/x86_64/openshift-origin36/"
      enabled: yes

    - name: centos-openshift-origin36-testing
      description: CentOS OpenShift Origin Testing
      baseurl: "http://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin36/"
      enabled: no
      gpgcheck: no

    - name: centos-openshift-origin36-debuginfo
      description: CentOS OpenShift Origin DebugInfo
      baseurl: http://debuginfo.centos.org/centos/7/paas/x86_64/
      enabled: no

    - name: centos-openshift-origin36-source
      description: CentOS OpenShift Origin Source
      baseurl: http://vault.centos.org/centos/7/paas/Source/openshift-origin36/
      enabled: no
  when:
    - openshift36_repo.stat.exists

- name: importing openshift-origin36 key
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-PaaS
  when:
    - openshift36_repo.stat.exists
